CREATE TABLE IF NOT EXISTS tmp_unittest_table (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
firstname VARCHAR(30) NOT NULL,
lastname VARCHAR(30) NOT NULL,
email VARCHAR(100),
registrationdate TIMESTAMP
)